### ISSUE TITLE
[Feature Request] "Lock on" to a point.

### ISSUE THREAD

**Issue by CyberSecGuy** [daipenger/BauerCam#2]
Camera Studio Mod had something similar, you could select a block to focus on, and it would track that block (think: Motion Tracking in After Effects) while going through the path system. This allows you to create smooth elliptical shots or circling shots. (I don't know the technical terms.)

Thank you SOOO much for bringing these to 1.10.2!

**Comment by daipenger** [comment]
Indeed, a very nice feature. Others were requesting that, too.
Implemented in BauerCam 1.9! :)
