### ISSUE TITLE
Kamera dreht durch

### ISSUE THREAD

**Issue by alexanderhorner** [daipenger/BauerCam#3]
Die Kamera dreht sich zwischen manchen punkten immer komisch um sich selbst. Das passiert jeden Durchgang zwischen denselben Points. Ich hab schon ein paar stellen gefixt in dem ich mich zu den Punkten mit /cam goto hingeportet habe und dann den jeweiligen Punkt replaced habe (funktioniert aber nicht bei jeder 'Stelle'). Hab erst gerade gemerkt, dass Sie aus Deutschland kommen. Ich kann auch ein Video machen wenn Sie Sich das genauer anschauen wollen.

**Comment by daipenger** [comment]
Der Rotationswinkel wird in Minecraft nicht in einen Bereich, der 360 Grad umfasst, normalisiert. Ich habe das ganze als mehr oder weniger gewolltes/nützliches Verhalten aufgefasst und normalisiere den Winkel daher auch nicht. Das heißt, dass wenn man sich während des Setzens zweier Punkte um die eigene Achse dreht, wird diese Bewegung auch in der Kamerfahrt umgesetzt werden.

Wenn einem das passiert und man das nicht wollte, dann ist der Fix eigentlich trivial: Zum Punkt teleportieren, Winkel korrigieren und Punkt ersetzen.
Bevor ich aber von etwas anderem spreche, sehe ich mir gerne auch ein Video an. (Oder einfach den Kamerapfad exportieren und hier posten)

Übrigens: Kannst mich auch mit Du ansprechen :)

Probably, won’t fix

**Comment by daipenger** [comment]
"/cam goto", "/cam replace" workflow was actually buggy! Fixed by v1.13.
Closed.
