### ISSUE TITLE
chunks dont load

### ISSUE THREAD

**Issue by seema84** [daipenger/BauerCam#6]
In Minecraft 1.11 werden die Chunks bei der Kamerafahrt nicht nachgeladen.

**Comment by seema84** [comment]
Ok im Singleplayer geht es nur auf Server nicht.

**Comment by seema84** [comment]
Es liegt wohl an Bukkit/Spigot und den "moved-too-quickly" Einstellungen. Daher schließe ich das Problem.

**Comment by daipenger** [comment]
Ja, dafür wird auch absichtlich der tp command abgesetzt, wenn potenziell große Distanzen überwunden werden. Wenn der nicht akzeptiert wird (Fehlende Rechte, Plugins überschreiben /tp und akzeptieren die vorgesehene Syntax nicht, etc.) gibt es Probleme mit Desync.
Das ist eine der Stellen, die mir am wenigsten im Code gefällt, man kann daran allerdings nicht viel tun. (Kannst dir ja gerne den Kommentar im Code dort ansehen, siehe Utils.java)
Ohnehin ist das Aufnehmen in Hinsicht auf Minema auf Servern allerdings unerwünscht.

**Comment by seema84** [comment]
Ich weiss nicht ob das Cam Studio auch tp commands dafür verwendet, allerdings gab es damit diese Probleme nicht. In Spigot zb. kann man den moved-too-quickly Wert einfach hochsetzen um das Problem zu umgehen. Was ich allerdings komisch finde, und das liegt an Vanilla, dass moved-too-quickly überhaupt im Gamemode 1 mit OP Rechte greift. Das macht aus meiner Sicht keinen großen Sinn.
